# Generated by Django 2.0.5 on 2018-10-11 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vid_corner_app', '0002_video_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=700)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vid_corner_app.Video_Upload')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='header_picture',
            field=models.ImageField(blank=True, default='vid_corner_app/profile_pics/defaultheader.jpg', null=True, upload_to='vid_corner_app/profile_pics'),
        ),
    ]
