# Generated by Django 2.0.5 on 2018-10-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_corner_app', '0005_videodislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_upload',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
