# Generated by Django 2.0.5 on 2018-10-12 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vid_corner_app', '0006_video_upload_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_from', to=settings.AUTH_USER_MODEL)),
                ('subscriber_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
